/**
 * AI Presentation & Slidedeck Studio API route
 */
export default async function slidesRoute(fastify) {
  fastify.post("/v1/slides/generate", async (request, reply) => {
    const { topic, theme = "dark", slideCount = 5 } = request.body || {};

    if (!topic || typeof topic !== "string" || !topic.trim()) {
      return reply.status(400).send({ error: "Topic or document content is required." });
    }

    const title = topic.split("\n")[0].slice(0, 60);

    const slides = [
      {
        title: title,
        subtitle: "Generated by Kyro AI Presentation Studio",
        type: "title",
        bullets: [
          "Overview of architecture & core principles",
          "Technical capabilities & scalability benchmark",
          "Implementation roadmap & execution plan",
        ],
        speakerNotes: "Welcome everyone. Today we are walking through the core concepts of this presentation.",
      },
      {
        title: "Key Objectives & Problem Statement",
        subtitle: "Context & Strategic Alignment",
        type: "content",
        bullets: [
          "High-throughput processing required for modern workloads",
          "Automated decision making with sub-100ms response times",
          "Zero downtime deployment strategy with fault tolerance",
        ],
        speakerNotes: "Focus heavily on the performance and reliability requirements outlined here.",
      },
      {
        title: "Architecture & Data Pipeline",
        subtitle: "System Diagram & Component Topology",
        type: "code",
        codeSnippet: `// Kyro Execution Flow
const pipeline = new KyroPipeline({
  model: "kyro-coder-pro",
  concurrency: 50,
  telemetry: true
});
await pipeline.execute(dataset);`,
        bullets: [
          "Decoupled event-driven architecture",
          "OpenAI SDK compatible REST gateway",
          "Real-time token soft cap enforcement",
        ],
        speakerNotes: "This code block demonstrates how simple it is to initialize the processing pipeline.",
      },
      {
        title: "Performance Benchmarks & Metrics",
        subtitle: "Empirical Runtime Verification",
        type: "stats",
        stats: [
          { label: "TTFT Latency", value: "< 45ms" },
          { label: "Token Throughput", value: "1,250 tok/s" },
          { label: "System Uptime", value: "99.99%" },
        ],
        bullets: [
          "Sub-50ms Time To First Token (TTFT)",
          "Sustained load handling across 10k concurrent sessions",
        ],
        speakerNotes: "Point out the TTFT latency benchmark compared to industry averages.",
      },
      {
        title: "Next Steps & Roadmap",
        subtitle: "Action Items & Execution Milestones",
        type: "summary",
        bullets: [
          "Phase 1: Roll out API keys and developer dashboard access",
          "Phase 2: Enable real-time telemetry webhooks",
          "Phase 3: Scale enterprise cluster across multi-region edge",
        ],
        speakerNotes: "Conclude with clear call to action and open the floor for Q&A.",
      },
    ];

    return reply.send({
      success: true,
      topic,
      theme,
      presentationTitle: title,
      totalSlides: slides.length,
      slides,
      generatedAt: new Date().toISOString(),
    });
  });
}
