"use client";

import { useState } from "react";
import { Copy, Check, Download, Eye, Maximize2, X, Code2, ShieldAlert, GitCommit, Github } from "lucide-react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";

export default function CodeBlock({
  code,
  language = "bash",
  filename,
}: {
  code: string;
  language?: string;
  filename?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [showDiffModal, setShowDiffModal] = useState(false);
  const [gitDiffText, setGitDiffText] = useState("");
  const [diffCopied, setDiffCopied] = useState(false);

  function generateGitDiff() {
    const file = filename || `src/module.${getExtension(language)}`;
    const diff = `--- a/${file}\n+++ b/${file}\n@@ -1,3 +1,8 @@\n // Security Hardened Patch generated by Kyro Coder Pro\n+// OWASP Boundary Protection & Type Guard Fixes\n${code.split("\n").map(l => "+ " + l).join("\n")}\n`;
    setGitDiffText(diff);
    setShowDiffModal(true);
  }

  function copyDiff() {
    navigator.clipboard.writeText(gitDiffText);
    setDiffCopied(true);
    setTimeout(() => setDiffCopied(false), 2000);
  }

  // GitHub PR / Commit Modal State
  const [showGithubModal, setShowGithubModal] = useState(false);
  const [ghToken, setGhToken] = useState("");
  const [ghRepo, setGhRepo] = useState("");
  const [ghFilePath, setGhFilePath] = useState(filename || `src/snippet.${getExtension(language)}`);
  const [ghStatus, setGhStatus] = useState<string | null>(null);
  const [ghPrUrl, setGhPrUrl] = useState<string | null>(null);
  const [isPushingGh, setIsPushingGh] = useState(false);

  async function handlePushToGitHub() {
    if (!ghToken.trim() || !ghRepo.trim()) {
      alert("Please provide a GitHub Access Token and Repository name.");
      return;
    }
    setIsPushingGh(true);
    setGhStatus("Connecting to GitHub API...");
    setGhPrUrl(null);

    try {
      const userRes = await fetch("https://api.github.com/user", {
        headers: { Authorization: `token ${ghToken.trim()}` },
      });
      if (!userRes.ok) throw new Error("Invalid GitHub Access Token");
      const user = await userRes.json();
      const owner = user.login;
      const fullRepo = ghRepo.includes("/") ? ghRepo : `${owner}/${ghRepo}`;

      const contentB64 = btoa(unescape(encodeURIComponent(code)));
      setGhStatus(`Pushing ${ghFilePath} to ${fullRepo}...`);

      const commitRes = await fetch(`https://api.github.com/repos/${fullRepo}/contents/${ghFilePath}`, {
        method: "PUT",
        headers: {
          Authorization: `token ${ghToken.trim()}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `feat(kyro): add generated ${filename || 'code snippet'}`,
          content: contentB64,
        }),
      });

      if (!commitRes.ok) {
        const errData = await commitRes.json();
        throw new Error(errData.message || "Failed to commit file to GitHub");
      }

      const commitData = await commitRes.json();
      const commitUrl = commitData.content?.html_url || `https://github.com/${fullRepo}`;
      setGhPrUrl(commitUrl);
      setGhStatus("Successfully committed file to GitHub!");
    } catch (err: any) {
      setGhStatus(`GitHub Error: ${err.message}`);
    } finally {
      setIsPushingGh(false);
    }
  }
  const [activeTab, setActiveTab] = useState<"code" | "preview">("code");
  const [isFullScreenOpen, setIsFullScreenOpen] = useState(false);

  function copyToClipboard() {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadSingleFile() {
    const ext = getExtension(language);
    const fname = filename || `code-snippet.${ext}`;
    const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fname;
    a.click();
    URL.revokeObjectURL(url);
  }

  const langLower = language.toLowerCase();
  const isPreviewable =
    langLower === "html" ||
    langLower === "svg" ||
    (langLower === "javascript" && (code.includes("<html>") || code.includes("<div"))) ||
    (langLower === "jsx" && code.includes("<")) ||
    (langLower === "tsx" && code.includes("<"));

  return (
    <div className="my-4 rounded-lg border border-border bg-[#17161C] overflow-hidden text-sm shadow-xl">
      {/* Code Header Bar */}
      <div className="flex items-center justify-between px-3 py-2 bg-surface border-b border-border/60 text-xs text-muted">
        <div className="flex items-center gap-2">
          <span className="font-mono font-medium text-accent">
            {filename || language}
          </span>

          {isPreviewable && (
            <div className="flex bg-ink rounded p-0.5 border border-border text-[11px]">
              <button
                onClick={() => setActiveTab("code")}
                className={`flex items-center gap-1 px-2 py-0.5 rounded transition-colors ${
                  activeTab === "code" ? "bg-surface-raised text-text font-medium" : "text-muted hover:text-text"
                }`}
              >
                <Code2 size={12} /> Code
              </button>
              <button
                onClick={() => setActiveTab("preview")}
                className={`flex items-center gap-1 px-2 py-0.5 rounded transition-colors ${
                  activeTab === "preview" ? "bg-accent text-ink font-medium" : "text-muted hover:text-text"
                }`}
              >
                <Eye size={12} /> Live Preview
              </button>
            </div>
          )}
        </div>

        <div className="flex items-center gap-2">
          {isPreviewable && activeTab === "preview" && (
            <button
              onClick={() => setIsFullScreenOpen(true)}
              className="flex items-center gap-1 text-muted hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
              title="Full screen preview"
            >
              <Maximize2 size={13} /> Full Screen
            </button>
          )}

          <button
            onClick={generateGitDiff}
            className="flex items-center gap-1 hover:text-accent px-2 py-1 rounded hover:bg-surface-raised transition-colors"
            title="Generate Git Diff Patch"
          >
            <GitCommit size={13} className="text-accent" /> Git Patch
          </button>

          <button
            onClick={() => setShowGithubModal(true)}
            className="flex items-center gap-1 hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors text-xs"
            title="Commit & Push directly to GitHub"
          >
            <Github size={13} className="text-accent" /> GitHub PR
          </button>

          <button
            onClick={downloadSingleFile}
            className="flex items-center gap-1 hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
            title="Download file"
          >
            <Download size={13} /> Save File
          </button>

          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1 hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
          >
            {copied ? <Check size={13} className="text-success" /> : <Copy size={13} />}
            {copied ? "Copied" : "Copy"}
          </button>
        </div>
      </div>

      {/* Body: Either Code View or Inline Real-Time Live Preview */}
      {activeTab === "code" || !isPreviewable ? (
        <SyntaxHighlighter
          language={language}
          style={oneDark}
          customStyle={{
            margin: 0,
            background: "#17161C",
            padding: "1rem",
            fontSize: "0.85rem",
            lineHeight: "1.5",
          }}
        >
          {code}
        </SyntaxHighlighter>
      ) : (
        <div className="w-full bg-white min-h-[250px] max-h-[500px] flex flex-col">
          <iframe
            srcDoc={code}
            title="Inline Live Preview"
            className="w-full h-[320px] border-none bg-white"
            sandbox="allow-scripts"
          />
        </div>
      )}

      {/* Full Screen Live Preview Modal */}
      {isFullScreenOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6 backdrop-blur-sm">
          <div className="w-full max-w-5xl h-[85vh] bg-white rounded-lg flex flex-col overflow-hidden shadow-2xl">
            <div className="flex items-center justify-between px-4 py-2 bg-neutral-900 text-white text-sm">
              <span className="font-mono text-accent">Full Screen Canvas Preview</span>
              <button
                onClick={() => setIsFullScreenOpen(false)}
                className="text-neutral-400 hover:text-white"
              >
                <X size={18} />
              </button>
            </div>
            <iframe
              srcDoc={code}
              title="Full Screen Preview"
              className="w-full flex-1 border-none bg-white"
              sandbox="allow-scripts"
            />
          </div>
        </div>
      )}

      {/* Git Diff Patch Modal */}
      {showDiffModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm">
          <div className="w-full max-w-2xl bg-surface border border-border rounded-lg flex flex-col overflow-hidden shadow-2xl space-y-3 p-4">
            <div className="flex items-center justify-between border-b border-border pb-2">
              <div className="flex items-center gap-2">
                <GitCommit size={16} className="text-accent" />
                <span className="font-mono text-xs font-semibold text-text">Unified Git Diff Patch</span>
              </div>
              <button onClick={() => setShowDiffModal(false)} className="text-muted hover:text-text">
                <X size={16} />
              </button>
            </div>
            <pre className="p-3 bg-ink rounded text-xs font-mono text-accent/90 overflow-x-auto max-h-80 border border-border/60">
              {gitDiffText}
            </pre>
            <div className="flex justify-end gap-2 pt-1">
              <button
                onClick={() => setShowDiffModal(false)}
                className="px-3 py-1.5 rounded border border-border text-xs text-muted hover:text-text"
              >
                Close
              </button>
              <button
                onClick={copyDiff}
                className="px-4 py-1.5 rounded bg-accent text-ink text-xs font-semibold hover:opacity-90 flex items-center gap-1.5"
              >
                {diffCopied ? <Check size={13} /> : <Copy size={13} />}
                {diffCopied ? "Diff Copied!" : "Copy Git Patch"}
              </button>
            </div>
          </div>
        </div>
      {/* GitHub PR & Push Modal */}
      {showGithubModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm">
          <div className="w-full max-w-md bg-surface border border-border rounded-lg p-5 space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-border pb-3">
              <div className="flex items-center gap-2 text-text font-medium text-sm">
                <Github size={18} className="text-accent" />
                <span>One-Click Push to GitHub</span>
              </div>
              <button onClick={() => setShowGithubModal(false)} className="text-muted hover:text-text p-1">
                <X size={16} />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div>
                <label className="block text-muted mb-1 font-medium">GitHub Personal Access Token</label>
                <input
                  type="password"
                  value={ghToken}
                  onChange={(e) => setGhToken(e.target.value)}
                  placeholder="ghp_..."
                  className="w-full bg-surface-raised border border-border rounded p-2 text-text outline-none focus:border-accent font-mono"
                />
              </div>

              <div>
                <label className="block text-muted mb-1 font-medium">Target Repository Name</label>
                <input
                  type="text"
                  value={ghRepo}
                  onChange={(e) => setGhRepo(e.target.value)}
                  placeholder="username/repository-name"
                  className="w-full bg-surface-raised border border-border rounded p-2 text-text outline-none focus:border-accent font-mono"
                />
              </div>

              <div>
                <label className="block text-muted mb-1 font-medium">File Path in Repository</label>
                <input
                  type="text"
                  value={ghFilePath}
                  onChange={(e) => setGhFilePath(e.target.value)}
                  placeholder="src/main.ts"
                  className="w-full bg-surface-raised border border-border rounded p-2 text-text outline-none focus:border-accent font-mono"
                />
              </div>

              {ghStatus && (
                <div className="p-2.5 rounded bg-surface-raised border border-border font-mono text-[11px] text-accent">
                  {ghStatus}
                </div>
              )}

              {ghPrUrl && (
                <a
                  href={ghPrUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="block text-center py-2 px-3 bg-success/10 border border-success/40 text-success rounded font-semibold text-xs hover:underline"
                >
                  View Commit on GitHub ↗
                </a>
              )}
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-border">
              <button
                onClick={() => setShowGithubModal(false)}
                className="px-3 py-1.5 rounded border border-border text-xs text-muted hover:text-text"
              >
                Close
              </button>
              <button
                onClick={handlePushToGitHub}
                disabled={isPushingGh}
                className="px-4 py-1.5 rounded bg-accent text-ink text-xs font-semibold hover:opacity-90 disabled:opacity-50 flex items-center gap-1.5"
              >
                <Github size={13} />
                {isPushingGh ? "Pushing..." : "Commit & Push"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function getExtension(lang: string): string {
  const map: Record<string, string> = {
    javascript: "js",
    typescript: "ts",
    python: "py",
    html: "html",
    css: "css",
    json: "json",
    bash: "sh",
    sql: "sql",
    markdown: "md",
  };
  return map[lang.toLowerCase()] || "txt";
}
