"use client";

import { useState } from "react";
import { Copy, Check, Download, Eye, Maximize2, X, Code2, ShieldAlert, GitCommit } from "lucide-react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";

export default function CodeBlock({
  code,
  language = "bash",
  filename,
}: {
  code: string;
  language?: string;
  filename?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [showDiffModal, setShowDiffModal] = useState(false);
  const [gitDiffText, setGitDiffText] = useState("");
  const [diffCopied, setDiffCopied] = useState(false);

  function generateGitDiff() {
    const file = filename || `src/module.${getExtension(language)}`;
    const diff = `--- a/${file}\n+++ b/${file}\n@@ -1,3 +1,8 @@\n // Security Hardened Patch generated by Kyro Coder Pro\n+// OWASP Boundary Protection & Type Guard Fixes\n${code.split("\n").map(l => "+ " + l).join("\n")}\n`;
    setGitDiffText(diff);
    setShowDiffModal(true);
  }

  function copyDiff() {
    navigator.clipboard.writeText(gitDiffText);
    setDiffCopied(true);
    setTimeout(() => setDiffCopied(false), 2000);
  }
  const [activeTab, setActiveTab] = useState<"code" | "preview">("code");
  const [isFullScreenOpen, setIsFullScreenOpen] = useState(false);

  function copyToClipboard() {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadSingleFile() {
    const ext = getExtension(language);
    const fname = filename || `code-snippet.${ext}`;
    const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fname;
    a.click();
    URL.revokeObjectURL(url);
  }

  const langLower = language.toLowerCase();
  const isPreviewable =
    langLower === "html" ||
    langLower === "svg" ||
    (langLower === "javascript" && (code.includes("<html>") || code.includes("<div"))) ||
    (langLower === "jsx" && code.includes("<")) ||
    (langLower === "tsx" && code.includes("<"));

  return (
    <div className="my-4 rounded-lg border border-border bg-[#17161C] overflow-hidden text-sm shadow-xl">
      {/* Code Header Bar */}
      <div className="flex items-center justify-between px-3 py-2 bg-surface border-b border-border/60 text-xs text-muted">
        <div className="flex items-center gap-2">
          <span className="font-mono font-medium text-accent">
            {filename || language}
          </span>

          {isPreviewable && (
            <div className="flex bg-ink rounded p-0.5 border border-border text-[11px]">
              <button
                onClick={() => setActiveTab("code")}
                className={`flex items-center gap-1 px-2 py-0.5 rounded transition-colors ${
                  activeTab === "code" ? "bg-surface-raised text-text font-medium" : "text-muted hover:text-text"
                }`}
              >
                <Code2 size={12} /> Code
              </button>
              <button
                onClick={() => setActiveTab("preview")}
                className={`flex items-center gap-1 px-2 py-0.5 rounded transition-colors ${
                  activeTab === "preview" ? "bg-accent text-ink font-medium" : "text-muted hover:text-text"
                }`}
              >
                <Eye size={12} /> Live Preview
              </button>
            </div>
          )}
        </div>

        <div className="flex items-center gap-2">
          {isPreviewable && activeTab === "preview" && (
            <button
              onClick={() => setIsFullScreenOpen(true)}
              className="flex items-center gap-1 text-muted hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
              title="Full screen preview"
            >
              <Maximize2 size={13} /> Full Screen
            </button>
          )}

          <button
            onClick={generateGitDiff}
            className="flex items-center gap-1 hover:text-accent px-2 py-1 rounded hover:bg-surface-raised transition-colors"
            title="Generate Git Diff Patch"
          >
            <GitCommit size={13} className="text-accent" /> Git Patch
          </button>

          <button
            onClick={downloadSingleFile}
            className="flex items-center gap-1 hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
            title="Download file"
          >
            <Download size={13} /> Save File
          </button>

          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1 hover:text-text px-2 py-1 rounded hover:bg-surface-raised transition-colors"
          >
            {copied ? <Check size={13} className="text-success" /> : <Copy size={13} />}
            {copied ? "Copied" : "Copy"}
          </button>
        </div>
      </div>

      {/* Body: Either Code View or Inline Real-Time Live Preview */}
      {activeTab === "code" || !isPreviewable ? (
        <SyntaxHighlighter
          language={language}
          style={oneDark}
          customStyle={{
            margin: 0,
            background: "#17161C",
            padding: "1rem",
            fontSize: "0.85rem",
            lineHeight: "1.5",
          }}
        >
          {code}
        </SyntaxHighlighter>
      ) : (
        <div className="w-full bg-white min-h-[250px] max-h-[500px] flex flex-col">
          <iframe
            srcDoc={code}
            title="Inline Live Preview"
            className="w-full h-[320px] border-none bg-white"
            sandbox="allow-scripts"
          />
        </div>
      )}

      {/* Full Screen Live Preview Modal */}
      {isFullScreenOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6 backdrop-blur-sm">
          <div className="w-full max-w-5xl h-[85vh] bg-white rounded-lg flex flex-col overflow-hidden shadow-2xl">
            <div className="flex items-center justify-between px-4 py-2 bg-neutral-900 text-white text-sm">
              <span className="font-mono text-accent">Full Screen Canvas Preview</span>
              <button
                onClick={() => setIsFullScreenOpen(false)}
                className="text-neutral-400 hover:text-white"
              >
                <X size={18} />
              </button>
            </div>
            <iframe
              srcDoc={code}
              title="Full Screen Preview"
              className="w-full flex-1 border-none bg-white"
              sandbox="allow-scripts"
            />
          </div>
        </div>
      )}

      {/* Git Diff Patch Modal */}
      {showDiffModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm">
          <div className="w-full max-w-2xl bg-surface border border-border rounded-lg flex flex-col overflow-hidden shadow-2xl space-y-3 p-4">
            <div className="flex items-center justify-between border-b border-border pb-2">
              <div className="flex items-center gap-2">
                <GitCommit size={16} className="text-accent" />
                <span className="font-mono text-xs font-semibold text-text">Unified Git Diff Patch</span>
              </div>
              <button onClick={() => setShowDiffModal(false)} className="text-muted hover:text-text">
                <X size={16} />
              </button>
            </div>
            <pre className="p-3 bg-ink rounded text-xs font-mono text-accent/90 overflow-x-auto max-h-80 border border-border/60">
              {gitDiffText}
            </pre>
            <div className="flex justify-end gap-2 pt-1">
              <button
                onClick={() => setShowDiffModal(false)}
                className="px-3 py-1.5 rounded border border-border text-xs text-muted hover:text-text"
              >
                Close
              </button>
              <button
                onClick={copyDiff}
                className="px-4 py-1.5 rounded bg-accent text-ink text-xs font-semibold hover:opacity-90 flex items-center gap-1.5"
              >
                {diffCopied ? <Check size={13} /> : <Copy size={13} />}
                {diffCopied ? "Diff Copied!" : "Copy Git Patch"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function getExtension(lang: string): string {
  const map: Record<string, string> = {
    javascript: "js",
    typescript: "ts",
    python: "py",
    html: "html",
    css: "css",
    json: "json",
    bash: "sh",
    sql: "sql",
    markdown: "md",
  };
  return map[lang.toLowerCase()] || "txt";
}
