"use client";

import { useState } from "react";
import { Monitor, Sparkles, ChevronLeft, ChevronRight, Download, FileText, Palette, Maximize2, Minimize2, Play, Code2 } from "lucide-react";
import { apiFetch } from "../../lib/api";

type Slide = {
  title: string;
  subtitle: string;
  type: "title" | "content" | "code" | "stats" | "summary";
  bullets: string[];
  codeSnippet?: string;
  stats?: { label: string; value: string }[];
  speakerNotes: string;
};

export default function SlidesPage() {
  const [topic, setTopic] = useState("Microservice Architecture Migration & Cost Optimization");
  const [theme, setTheme] = useState<"dark" | "gold" | "cyberpunk" | "minimal">("dark");
  const [isGenerating, setIsGenerating] = useState(false);
  const [slides, setSlides] = useState<Slide[]>([
    {
      title: "Microservice Architecture Migration",
      subtitle: "Generated by Kyro AI Presentation Studio",
      type: "title",
      bullets: [
        "Overview of decoupled event-driven services",
        "Empirical performance benchmarks & cost ROI",
        "Execution roadmap & zero-downtime strategy",
      ],
      speakerNotes: "Welcome everyone. Today we are walking through the core concepts of this presentation.",
    },
    {
      title: "Key Objectives & Technical Architecture",
      subtitle: "System Scalability & Resiliency",
      type: "content",
      bullets: [
        "High-throughput processing required for enterprise workloads",
        "Automated failover with sub-50ms Time To First Token (TTFT)",
        "Zero downtime deployment strategy with fault isolation",
      ],
      speakerNotes: "Focus heavily on the performance and reliability requirements outlined here.",
    },
    {
      title: "Execution Code Pipeline",
      subtitle: "OpenAI SDK Compatible Gateway",
      type: "code",
      codeSnippet: `// Kyro Processing Pipeline
import { KyroGateway } from "@kyro/sdk";

const gateway = new KyroGateway({ apiKey: process.env.KYRO_KEY });
const result = await gateway.chat.completions.create({
  model: "kyro-coder-pro",
  messages: [{ role: "user", content: "Optimize SQL query" }]
});`,
      bullets: [
        "100% OpenAI SDK drop-in compatibility",
        "Secret masking & PII filter active",
      ],
      speakerNotes: "Point out how effortless the integration is with existing Node.js projects.",
    },
    {
      title: "Performance & Cost Benchmarks",
      subtitle: "Empirical Runtime Verification",
      type: "stats",
      stats: [
        { label: "TTFT Latency", value: "< 45ms" },
        { label: "Throughput", value: "1,450 tok/s" },
        { label: "Cost Savings", value: "68% ROI" },
      ],
      bullets: [
        "Significant cost reduction compared to proprietary cloud LLMs",
        "Sub-50ms TTFT across 10,000 concurrent sessions",
      ],
      speakerNotes: "Highlight the cost savings metrics on this slide.",
    },
    {
      title: "Execution Roadmap & Next Steps",
      subtitle: "Implementation Milestones",
      type: "summary",
      bullets: [
        "Phase 1: Deploy Kyro API Gateway & issue developer keys",
        "Phase 2: Enable real-time telemetry webhooks",
        "Phase 3: Scale enterprise edge clusters",
      ],
      speakerNotes: "Conclude with clear call to action and open for questions.",
    },
  ]);

  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [showNotes, setShowNotes] = useState(false);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!topic.trim()) return;
    setIsGenerating(true);
    try {
      const res = await apiFetch("/v1/slides/generate", {
        method: "POST",
        body: JSON.stringify({ topic, theme }),
      });
      if (res.slides) {
        setSlides(res.slides);
        setCurrentIndex(0);
      }
    } catch (e: any) {
      alert(`Slide generation error: ${e.message}`);
    } finally {
      setIsGenerating(false);
    }
  }

  function downloadStandaloneHtml() {
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${slides[0]?.title || "Presentation"}</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #0A0D14; color: #F1F5F9; margin: 0; padding: 40px; }
    .slide { max-width: 900px; margin: 0 auto 40px auto; background: #131825; border: 1px solid #1E293B; border-radius: 12px; padding: 40px; box-shadow: 0 20px 25px -5px rgba(0,0,0,0.5); }
    h1 { color: #00E5FF; font-size: 32px; margin-top: 0; }
    h2 { color: #94A3B8; font-size: 16px; margin-bottom: 24px; font-weight: normal; }
    ul { line-height: 1.8; font-size: 18px; color: #CBD5E1; }
    pre { background: #0A0D14; padding: 20px; border-radius: 8px; border: 1px solid #1E293B; color: #00E5FF; font-family: monospace; }
  </style>
</head>
<body>
  ${slides
    .map(
      (s) => `
    <div class="slide">
      <h1>${s.title}</h1>
      <h2>${s.subtitle}</h2>
      ${s.codeSnippet ? `<pre><code>${s.codeSnippet}</code></pre>` : ""}
      <ul>${s.bullets.map((b) => `<li>${b}</li>`).join("")}</ul>
    </div>
  `
    )
    .join("")}
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${slides[0]?.title.toLowerCase().replace(/[^a-z0-9]/g, "-") || "presentation"}.html`;
    a.click();
  }

  const themeStyles = {
    dark: "bg-surface text-text border-border",
    gold: "bg-[#161208] text-[#FDE047] border-[#854D0E]",
    cyberpunk: "bg-[#090D16] text-[#FF007A] border-[#FF007A]/40",
    minimal: "bg-white text-slate-900 border-slate-200",
  };

  const activeSlide = slides[currentIndex] || slides[0];

  return (
    <div className="min-h-screen bg-bg text-text p-6 md:p-10 font-sans">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between border-b border-border pb-6 gap-4">
          <div>
            <h1 className="font-display text-2xl md:text-3xl font-bold flex items-center gap-3">
              <Monitor className="text-accent" size={30} /> AI Presentation & Slidedeck Studio
            </h1>
            <p className="text-sm text-muted mt-1">
              Type a topic or paste document content to generate interactive slide decks with custom themes & presenter notes.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={downloadStandaloneHtml}
              className="flex items-center gap-2 px-4 py-2 bg-surface-raised border border-border rounded font-medium text-xs text-text hover:border-accent transition-colors"
            >
              <Download size={14} /> Export HTML
            </button>
            <button
              onClick={() => setIsFullscreen(!isFullscreen)}
              className="flex items-center gap-2 px-4 py-2 bg-accent text-ink rounded font-semibold text-xs hover:opacity-90 transition-opacity"
            >
              <Play size={14} /> Present Mode
            </button>
          </div>
        </div>

        {/* Input Prompt & Theme Controls */}
        <form onSubmit={handleGenerate} className="bg-surface border border-border rounded-lg p-5 space-y-4">
          <div className="flex flex-col md:flex-row gap-3">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. Microservice Architecture Migration & Cost Optimization..."
              className="flex-1 bg-surface-raised border border-border rounded-lg px-4 py-3 text-sm text-text outline-none focus:border-accent font-sans"
            />
            <button
              type="submit"
              disabled={isGenerating}
              className="px-6 py-3 bg-accent text-ink rounded-lg font-semibold text-sm flex items-center gap-2 hover:opacity-90 transition-opacity"
            >
              <Sparkles size={16} /> {isGenerating ? "Generating..." : "Generate AI Slides"}
            </button>
          </div>

          {/* Theme Selector Pills */}
          <div className="flex items-center gap-3 pt-1">
            <span className="text-xs font-mono text-muted flex items-center gap-1">
              <Palette size={14} /> Color Theme:
            </span>
            <div className="flex gap-2">
              {(["dark", "gold", "cyberpunk", "minimal"] as const).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTheme(t)}
                  className={`px-3 py-1 rounded text-xs font-mono capitalize border transition-all ${
                    theme === t
                      ? "border-accent bg-accent/10 text-accent font-bold"
                      : "border-border text-muted hover:text-text"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
        </form>

        {/* Slide Preview Stage */}
        <div className="space-y-4">
          {/* Main Slide Canvas */}
          <div
            className={`w-full min-h-[420px] rounded-xl border p-8 md:p-12 flex flex-col justify-between transition-all shadow-2xl relative ${
              themeStyles[theme]
            }`}
          >
            {/* Top Slide Meta */}
            <div className="flex items-center justify-between border-b border-current/20 pb-4">
              <span className="text-xs font-mono uppercase tracking-widest opacity-70">
                Slide {currentIndex + 1} of {slides.length}
              </span>
              <span className="text-xs font-mono opacity-70">Kyro AI Studio</span>
            </div>

            {/* Slide Body */}
            <div className="my-8 space-y-6">
              <h2 className="font-display text-2xl md:text-4xl font-bold tracking-tight">{activeSlide.title}</h2>
              <p className="text-sm font-mono opacity-80">{activeSlide.subtitle}</p>

              {activeSlide.codeSnippet && (
                <pre className="bg-black/60 border border-current/30 rounded-lg p-4 font-mono text-xs overflow-x-auto text-accent">
                  <code>{activeSlide.codeSnippet}</code>
                </pre>
              )}

              {activeSlide.stats && (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-4">
                  {activeSlide.stats.map((s, idx) => (
                    <div key={idx} className="bg-black/40 border border-current/20 rounded-lg p-4 text-center">
                      <div className="font-display text-2xl font-bold">{s.value}</div>
                      <div className="text-xs font-mono opacity-80 mt-1">{s.label}</div>
                    </div>
                  ))}
                </div>
              )}

              <ul className="space-y-3 font-sans text-sm md:text-base leading-relaxed list-disc list-inside opacity-90">
                {activeSlide.bullets.map((b, idx) => (
                  <li key={idx}>{b}</li>
                ))}
              </ul>
            </div>

            {/* Bottom Controls Bar */}
            <div className="flex items-center justify-between border-t border-current/20 pt-4">
              <button
                onClick={() => setCurrentIndex((prev) => Math.max(prev - 1, 0))}
                disabled={currentIndex === 0}
                className="flex items-center gap-1 text-xs font-mono disabled:opacity-30 hover:opacity-100"
              >
                <ChevronLeft size={16} /> Previous
              </button>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => setShowNotes(!showNotes)}
                  className="px-3 py-1 bg-black/30 border border-current/20 rounded text-xs font-mono hover:bg-black/50"
                >
                  {showNotes ? "Hide Presenter Notes" : "View Speaker Notes"}
                </button>
              </div>

              <button
                onClick={() => setCurrentIndex((prev) => Math.min(prev + 1, slides.length - 1))}
                disabled={currentIndex === slides.length - 1}
                className="flex items-center gap-1 text-xs font-mono disabled:opacity-30 hover:opacity-100"
              >
                Next <ChevronRight size={16} />
              </button>
            </div>
          </div>

          {/* Speaker Notes Drawer */}
          {showNotes && (
            <div className="bg-surface border border-border rounded-lg p-4 space-y-2">
              <h4 className="text-xs font-mono font-bold text-accent flex items-center gap-2">
                <FileText size={14} /> Speaker Notes (Slide {currentIndex + 1})
              </h4>
              <p className="text-xs text-muted font-sans leading-relaxed">
                {activeSlide.speakerNotes}
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
